import "./globals.css";
import type { Metadata } from "next";

import StoreProvider from "@/libs/redux/StoreProvider";

import React from "react";
import RootStyleRegistry from "@/libs/theme/RootStyleRegistry";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body>
				<StoreProvider>
					<RootStyleRegistry>{children}</RootStyleRegistry>
				</StoreProvider>
			</body>
		</html>
	);
}
