import "./globals.css";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import ThemeProviderApp from "@/libs/theme/ThemeProvider";
import StoreProvider from "@/libs/redux/StoreProvider";

import React from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<AppRouterCacheProvider options={{ key: "css" }}>
						<ThemeProviderApp>{children}</ThemeProviderApp>
					</AppRouterCacheProvider>
				</StoreProvider>
			</body>
		</html>
	);
}
