import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/libs/redux/StoreProvider";
import React from "react";

import dynamic from "next/dynamic";
const RootStyleRegistry = dynamic(
	() => import("@/libs/theme/RootStyleRegistry"),
	{ ssr: false }
);
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<StoreProvider>
					<RootStyleRegistry>{children}</RootStyleRegistry>
				</StoreProvider>
			</body>
		</html>
	);
}
